export enum SocketEventType {
  NEW_FRIEND_REQUEST = 'NEW_FRIEND_REQUEST',
  ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST',
  REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST',
  CANCEL_FRIEND_REQUEST = 'CANCEL_FRIEND_REQUEST',
  DELETE_FRIEND = 'DELETE_FRIEND'
}
